PsychologicalTestApp/Models/Enums/TestType.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace PsychologicalTestApp.Models.Enums
{
    public enum TestType
    {
        [Display(Name = "Dla dzieci")]
        Child,
        [Display(Name = "Dla dorosłych")]
        Adult
    }
}

PsychologicalTestApp/Models/Participant.cs
using PsychologicalTestApp.Models.Enums;
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PsychologicalTestApp.Models
{
    public class Participant 
    {       
        [Required]
        [Key]
        public string Id { get; set; }

        [Display(Name = "Imię")]
        public string FirstName { get; set; }

        [Display(Name = "Nazwisko")]
        public string LastName { get; set; }

        [Range(1, 116)]
        [Display(Name = "Wiek")]
        public int Age { get; set; }

        [Display(Name = "Płeć")]
        public Gender? Gender { get; set; }

        [Display(Name = "Opis")]
        public string Description { get; set; }

        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [Phone]
        [Display(Name = "Numer telefonu")]
        public string PhoneNumber { get; set; }

        [Display(Name = "Utworzony")]
        [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime CreateDate { get; set; }

        [Display(Name = "Zedytowany")]
        [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime UpdateDate { get; set; }

        [Display(Name = "Potwierdzony")]
        public bool Confirm { get; set; }

        [Required]
        [ForeignKey(nameof(UserId))]        
        public string UserId { get; set; }
        public virtual User User { get; set; }

        [ForeignKey(nameof(TestId))]
        public string TestId { get; set; }
        public virtual Test Test { get; set; }
    }
}

PsychologicalTestApp/Models/Test.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace PsychologicalTestApp.Models
{
    public class Test
    {
        [Required]
        [Key]
        public string TestId { get; set; }

        [Required]
        public string Name { get; set; }

        [ForeignKey(nameof(CategoryId))]
        public int? CategoryId { get; set; }

        public virtual TestCategory Category { get; set; }

        public string Description { get; set; }

        public bool Solved { get; set; }

        public string Result { get; set; }

        [Required]
        [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime AddDate { get; internal set; }

        [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime SolvedDate { get; internal set; }

        public virtual ICollection<Participant> Participants { get; set; }
    }
}

PsychologicalTestApp/Controllers/ParticipantController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Infrastructure;
using PsychologicalTestApp.Data;
using PsychologicalTestApp.Models;
using PsychologicalTestApp.ViewModels;

namespace PsychologicalTestApp.Controllers
{
    public class ParticipantController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly AppDbContext _db;
        private IUserValidator<User> _userValidator;
        private IPasswordValidator<User> _passwordValidator;
        private readonly IActionContextAccessor _accessor;
        private IPasswordHasher<User> _passwordHasher;

        public ParticipantController(UserManager<User> userManager, AppDbContext db, IUserValidator<User> userValidator, IPasswordValidator<User> passwordValidator, IPasswordHasher<User> passwordHasher, IActionContextAccessor accessor)
        {
            _userManager = userManager;
            _db = db;
            _userValidator = userValidator;
            _passwordValidator = passwordValidator;
            _passwordHasher = passwordHasher;
            _accessor = accessor;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Update(string userId)
        {
            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                var participant = _db.Participants.FirstOrDefault(p => p.UserId == user.Id);
                if (participant == null)
                {
                    return NotFound();
                }
                ParticipantCreateEditVM participantVM = new ParticipantCreateEditVM { UserName = user.UserName, Email = participant.Email, FirstName = participant.FirstName, LastName = participant.LastName, Age = participant.Age, Gender = participant.Gender, Description = participant.Description, UserId = user.Id };

                return View(participantVM);
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(ParticipantCreateEditVM model)
        {
            if (ModelState.IsValid)
            {
                User user = await _userManager.FindByIdAsync(model.UserId);
                bool change_userName = false;
                bool change_firstName = false;
                bool change_lastName = false;
                bool change_description = false;
                bool change_email = false;
                bool change_password = false;
                bool change_age = false;
                bool change_gender = false;

                if (user != null)
                {
                    var participant = _db.Participants.FirstOrDefault(p => p.UserId == user.Id);

                    IdentityResult valid = await _userValidator.ValidateAsync(_userManager, user);

                    if (!string.IsNullOrEmpty(model.UserName) && model.UserName != user.UserName)
                    {
                        var old_userName = user.UserName;
                        user.UserName = model.UserName;
                        valid = await _userValidator.ValidateAsync(_userManager, user);
                        if (!valid.Succeeded)
                        {
                            AddErrorsFromResult(valid);
                            return View(model);
                        }

                        change_userName = true;
                    }

                    if (!string.IsNullOrEmpty(model.FirstName.Trim()) && model.FirstName.Trim() != participant.FirstName.Trim())
                    {
                        participant.FirstName = model.FirstName.Trim();
                        change_firstName = true;
                    }

                    if (!string.IsNullOrEmpty(model.LastName.Trim()) && model.LastName != participant.LastName.Trim())
                    {
                        participant.LastName = model.LastName.Trim();
                        change_lastName = true;
                    }

                    if (!string.IsNullOrEmpty(model.Description) && model.Description != participant.Description)
                    {
                        participant.Description = model.Description;
                        change_description = true;
                    }

                    if (model.Age != participant.Age)
                    {
                        if (model.Age <= 116 && model.Age >= 1)
                        {
                            participant.Age = model.Age.GetValueOrDefault();
                            change_age = true;
                        }
                        else
                        {
                            ModelState.AddModelError("age", "Niepoprawny wiek.");
                            return View(model);
                        }
                    }

                    if (model.Gender != participant.Gender)
                    {
                        if (!string.IsNullOrEmpty(model.Gender.ToString()))
                        {
                            participant.Gender = model.Gender;
                            change_gender = true;
                        }
                        else
                        {
                            ModelState.AddModelError("Gender", "Płeć jest wymagana.");
                            return View(model);
                        }
                    }

                    IdentityResult validEmail = await _userValidator.ValidateAsync(_userManager, user);
                    if (!string.IsNullOrEmpty(model.Email) && model.Email != user.Email)
                    {
                        user.Email = model.Email;
                        validEmail = await _userValidator.ValidateAsync(_userManager, user);
                        if (!validEmail.Succeeded)
                        {
                            AddErrorsFromResult(validEmail);
                            return View(model);
                        }
                        change_email = true;
                        participant.Email = model.Email;
                    }

                    IdentityResult validPass = null;
                    if ((!string.IsNullOrEmpty(model.Password)) && (model.Password == model.ConfirmPassword))
                    {
                        validPass = await _passwordValidator.ValidateAsync(_userManager, user, model.Password);
                        if (validPass.Succeeded)
                        {
                            user.PasswordHash = _passwordHasher.HashPassword(user, model.Password);
                            change_password = true;
                        }
                        else
                        {
                            AddErrorsFromResult(validPass);
                        }
                    }
                    else if (model.Password != model.ConfirmPassword)
                    {
                        ModelState.AddModelError("password", "Nowe hasło i powtórzone hasło muszą się zgadzać.");
                        return View(model);
                    }

                    if (change_userName || change_firstName || change_lastName || change_email || change_password || change_age || change_description || change_gender)
                    {
                        IdentityResult result = await _userManager.UpdateAsync(user);
                        if (result.Succeeded)
                        {
                            participant.UpdateDate = DateTime.Now;
                            _db.Update(participant);
                            _db.SaveChanges();
                            return RedirectToAction("Index");
                        }
                        else
                        {
                            AddErrorsFromResult(result);
                        }
                    }
                }
                else
                {
                    ModelState.AddModelError("username", "Nazwa użytkownika jest już zajęta.");
                }
            }

            return View(model);
        }

        [HttpGet]
        public IActionResult Tests()
        {
            var testListVM = new TestListVM()
            {
                Tests = _db.Tests.OrderByDescending(o => o.AddDate).ToList()
            };
            return View(testListVM);
        }

        private void AddErrorsFromResult(IdentityResult result)
        {
            foreach (IdentityError error in result.Errors)
            {
                if (error.Code.Contains("Password"))
                {
                    ModelState.AddModelError("password", error.Description);
                }
                else if (error.Code.Contains("User"))
                {
                    ModelState.AddModelError("username", error.Description);
                }
                else if (error.Code.Contains("Email"))
                {
                    ModelState.AddModelError("email", error.Description);
                }
                else
                {
                    ModelState.AddModelError("", error.Description);
                }
            }
        }
    }
}

PsychologicalTestApp/Controllers/TestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace PsychologicalTestApp.Controllers
{
    public class TestController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

PsychologicalTestApp/Views/Participant/Index.cshtml
@inject UserManager<User> UserManager
@inject AppDbContext Context
<link rel="stylesheet" href="~/css/index4.css" />

@section navbar_Participant {
    <section class="navbar">
        @Html.Partial("_Navbar_Participant")
    </section>
}
<div class="content_flex">
    <div class="container-fluid">
        <div class="row">
            <div class="col col-md-10" id="subheader"><h2>Szczegóły</h2></div>
            <hr />
        </div>
        <div class="row">
            <div class="col col-md-6">
                <h6>Imię:</h6>
            </div>
            <div class="col col-md-6" id="inf">
                @if (!string.IsNullOrEmpty(Context.Participants.FirstOrDefault(c => c.UserId == UserManager.GetUserId(User)).FirstName))
                {
                    @Context.Participants.FirstOrDefault(c => c.UserId == UserManager.GetUserId(User)).FirstName
                }
                else
                {
                    <span class="text-muted">
                        Brak
                    </span>
                }
            </div>
        </div>
        <div class="row">
            <div class="col col-md-6">
                <h6>Nazwisko:</h6>
            </div>
            <div class="col col-md-6" id="inf">
                @if (!string.IsNullOrEmpty(Context.Participants.FirstOrDefault(c => c.UserId == UserManager.GetUserId(User)).LastName))
                {
                    @Context.Participants.FirstOrDefault(c => c.UserId == UserManager.GetUserId(User)).LastName
                }
                else
                {
                    <span class="text-muted">
                        Brak
                    </span>
                }
            </div>
        </div>
        <div class="row">
            <div class="col col-md-6">
                <h6>Wiek:</h6>
            </div>
            <div class="col col-md-6" id="inf">
                @if (!Context.Participants.FirstOrDefault(c => c.UserId == UserManager.GetUserId(User)).Age.Equals(0))
                {
                    @Html.DisplayFor(modelItem => @Context.Participants.FirstOrDefault(c => c.UserId == UserManager.GetUserId(User)).Age)
                }
                else
                {
                    <span class="text-muted">
                        Brak
                    </span>
                }
            </div>
        </div>
        <div class="row">
            <div class="col col-md-6">
                <h6>Płeć:</h6>
            </div>
            <div class="col col-md-6" id="inf">
                @if (!string.IsNullOrEmpty(Context.Participants.FirstOrDefault(c => c.UserId == UserManager.GetUserId(User)).Gender.ToString()))
                {
                    @Html.DisplayFor(modelItem => @Context.Participants.FirstOrDefault(c => c.UserId == UserManager.GetUserId(User)).Gender)
                }
                else
                {
                    <span class="text-muted">
                        Brak
                    </span>
                }
            </div>
        </div>
        <div class="row">
            <div class="col col-md-6">
                <h6>Email:</h6>
            </div>
            <div class="col col-md-6" id="inf">
                @Context.Participants.FirstOrDefault(c => c.UserId == UserManager.GetUserId(User)).Email
            </div>
        </div>
    </div>

</div>

PsychologicalTestApp/Views/Participant/Tests.cshtml
@model TestListVM
@inject AppDbContext Context
<link rel="stylesheet" href="~/css/index5.css" />

@section navbar {
    <section class="navbar">
        @Html.Partial("_Navbar_Participant")
    </section>
}

@{
    ViewBag.Title = "Lista testów";
}

<div class="container_flex">
    <div class="content-fluid">
        <div class="row" id="title">
            <div class="col-sm-10">
                <h2>@ViewBag.Title</h2>
            </div>
            <div class="col-sm-2" style="float: right;">
                <div class="" style="float: right;">
                    <a href="@Url.Action("CreateTest")" class="btn pull-right">
                        <i class="material-icons" id="icon" data-toggle="tooltip" data-placement="bottom" title="Dodaj">&#xE147;</i>
                    </a>
                </div>
            </div>
        </div>

        @if (Model.Tests.ToList().Count > 0)
        {
            <div class="table-response">
                <table class="table table-striped table-condensed table-hover">
                    <thead>
                        <tr>
                            <th scope="col"><strong>#</strong></th>
                            <th scope="col">Nazwa</th>
                            <th scope="col">Kategoria</th>
                            <th scope="col">Opis</th>
                            <th scope="col">Wynik</th>
                        </tr>
                    </thead>
                    <tbody>
                        @{
                            var i = 0;
                            foreach (var item in Model.Tests.ToList())
                            {
                                i++;
                                <tr>
                                    <td>
                                        @i
                                    </td>
                                    <td>
                                        @if (!string.IsNullOrEmpty(item.Name))
                                        {                                           
                                            <strong></strong><a asp-area="" asp-controller="Test" asp-action="">@item.Name</a>
                                        }
                                        else
                                        {
                                            <span class="text-muted">
                                                Brak
                                            </span>

                                        }


                                    </td>
                                    <td>
                                        @if (!string.IsNullOrEmpty(@Context.TestCategory.FirstOrDefault(c => c.CategoryId == item.CategoryId).Name))
                                        {
                                            @if (@Context.TestCategory.FirstOrDefault(c => c.CategoryId == item.CategoryId).Name.Contains("Adult"))
                                            {
                                                <span>Dla dorosłych</span>
                                            }
                                            else
                                            {
                                                <span>Dla dzieci</span>
                                            }
                                        }
                                        else
                                        {
                                            <span class="text-muted">
                                                Brak
                                            </span>
                                        }

                                    </td>
                                    <td>

                                        @if (!string.IsNullOrEmpty(item.Description))
                                        {
                                            @item.Description
                                        }
                                        else
                                        {
                                            <span class="text-muted">
                                                Brak
                                            </span>

                                        }

                                    </td>
                                    <td>

                                        @if (item.Solved)
                                        {
                                            @item.Result
                                        }
                                        else
                                        {
                                            <span class="text-muted">
                                                Brak
                                            </span>

                                        }

                                    </td>

                                </tr>
                            }
                        }
                    </tbody>
                </table>
            </div>

        }
    </div>
</div>

PsychologicalTestApp/Views/Participant/Update.cshtml
@model ParticipantCreateEditVM
@section navbar_Admin {
    <section class="navbar_Participant">
        @Html.Partial("_Navbar_Participant")
    </section>
}

<link rel="stylesheet" href="~/css/create_user1.css" />

<div class="content_flex">
    <div class="card">
        <div class="card-header">
            <h3><strong>Edycja</strong></h3>
            <button onclick="window.location.href='Index'" type="button" class="close">&times;</button>
        </div>
        <div class="card-body">
            <form asp-action="Update" asp-controller="Participant" method="post" class="form-horizontal" role="form">
                <div asp-validation-summary="ModelOnly" id="summary" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="UserName" class="control-label"></label>
                    <input asp-for="UserName" class="form-control" placeholder="@Model.UserName">
                    <span asp-validation-for="UserName" class="text-danger"></span>
                </div>
                <label class="person-label">Zmiana hasła</label>
                <hr />
                <div class="form-group">
                    <label asp-for="OldPassword" class="control-label"></label>
                    <input asp-for="OldPassword" class="form-control">
                    <span asp-validation-for="OldPassword" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Password" class="control-label"></label>
                    <input type="password" asp-for="Password" class="form-control">
                    <span asp-validation-for="Password" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ConfirmPassword" class="control-label"></label>
                    <input type="password" asp-for="ConfirmPassword" class="form-control">
                    <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                </div>
                <label class="person-label">Dane osobowe</label>
                <div class="card-footer">
                    <div class="form-group">
                        <label asp-for="FirstName" class="control-label"></label>
                        <input type="text" asp-for="FirstName" class="form-control" placeholder="@Model.FirstName">
                        <span asp-validation-for="FirstName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="LastName" class="control-label"></label>
                        <input type="text" asp-for="LastName" class="form-control" placeholder="@Model.LastName">
                        <span asp-validation-for="LastName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Gender" class="control-label"></label>
                        <select class="form-control" asp-for="Gender" asp-items="Html.GetEnumSelectList(typeof(PsychologicalTestApp.Models.Enums.Gender))">
                            <option selected="selected" value="">Wybierz</option>
                        </select>
                        <span asp-validation-for="Gender" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Age" class="control-label"></label>
                        <input type="number" asp-for="Age" class="form-control" min="1" max="116" />
                        <span asp-validation-for="Age" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Email" class="control-label"></label>
                        <input type="email" asp-for="Email" class="form-control" placeholder="@Model.Email">
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                </div>
                <input asp-for="UserId" class="form-control" placeholder="@Model.UserId" hidden>
                <div class="form-group btn-group">
                    <input type="submit" value="Zapisz" class="btn create_btn">
                    <input type="reset" value="Wyczyść" class="btn cancel_btn">
                </div>
            </form>
        </div>
    </div>
</div>