PsychologicalTestApp/Models/Enums/TestType.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace PsychologicalTestApp.Models.Enums
{
    public enum TestType
    {
        [Display(Name = "Dla dzieci")]
        Child,
        [Display(Name = "Dla dorosłych")]
        Adult
    }
}

PsychologicalTestApp/Models/Participant.cs
using PsychologicalTestApp.Models.Enums;
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PsychologicalTestApp.Models
{
    public class Participant 
    {       
        [Required]
        [Key]
        public string Id { get; set; }

        [Display(Name = "Imię")]
        public string FirstName { get; set; }

        [Display(Name = "Nazwisko")]
        public string LastName { get; set; }

        [Range(1, 116)]
        [Display(Name = "Wiek")]
        public int Age { get; set; }

        [Display(Name = "Płeć")]
        public Gender? Gender { get; set; }

        [Display(Name = "Opis")]
        public string Description { get; set; }

        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [Phone]
        [Display(Name = "Numer telefonu")]
        public string PhoneNumber { get; set; }

        [Display(Name = "Utworzony")]
        [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime CreateDate { get; set; }

        [Display(Name = "Zedytowany")]
        [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime UpdateDate { get; set; }

        [Display(Name = "Potwierdzony")]
        public bool Confirm { get; set; }

        [Required]
        [ForeignKey(nameof(UserId))]        
        public string UserId { get; set; }
        public virtual User User { get; set; }

        [ForeignKey(nameof(TestId))]
        public string TestId { get; set; }
        public virtual Test Test { get; set; }
    }
}

PsychologicalTestApp/Models/Test.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace PsychologicalTestApp.Models
{
    public class Test
    {
        [Required]
        [Key]
        public string TestId { get; set; }

        [Required]
        public string Name { get; set; }

        [ForeignKey(nameof(CategoryId))]
        public int? CategoryId { get; set; }

        public virtual TestCategory Category { get; set; }

        public string Description { get; set; }

        public bool Solved { get; set; }

        public string Result { get; set; }

        [Required]
        [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime AddDate { get; internal set; }

        [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime SolvedDate { get; internal set; }

        public virtual ICollection<Participant> Participants { get; set; }
    }
}

PsychologicalTestApp/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PsychologicalTestApp.Data;
using PsychologicalTestApp.Models;
using PsychologicalTestApp.ViewModels;

namespace PsychologicalTestApp.Controllers
{
    //[Authorize(Roles = "Admin")]
    public class AdminController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly AppDbContext _db;
        private IUserValidator<User> _userValidator;
        private IPasswordValidator<User> _passwordValidator;
        private IPasswordHasher<User> _passwordHasher;
        public AdminController(UserManager<User> userManager, AppDbContext db, IUserValidator<User> userValidator, IPasswordValidator<User> passwordValidator, IPasswordHasher<User> passwordHasher)
        {
            _userManager = userManager;
            _db = db;
            _userValidator = userValidator;
            _passwordValidator = passwordValidator;
            _passwordHasher = passwordHasher;
        }
    
        [HttpGet]
        public IActionResult Index()
        {
            var model = new ParticipantListIndexVM(_db);
            model.PageSize = 10;
            model.OnGet(1);

            return View(model);
        }

        [HttpGet]
        public IActionResult CreateParticipant()
        {
            return View();
        }

        [HttpGet]
        public IActionResult CreateTest()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateParticipant(ParticipantCreateEditVM participantVM)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByEmailAsync(participantVM.Email);
                if (user == null)
                {
                    user = new User()
                    {
                        UserName = participantVM.UserName,
                        Email = participantVM.Email,
                        CreateDate = DateTime.Now,
                        EmailConfirmed = true
                    };
                    if (participantVM.Password == participantVM.ConfirmPassword)
                    {
                        var result = await _userManager.CreateAsync(user, participantVM.Password);

                        if (result.Succeeded)
                        {
                            await _userManager.AddToRoleAsync(user, "Participant");
                            await _userManager.AddClaimAsync(user, new Claim(ClaimTypes.Role, "Participant"));
                            Participant participant = new Participant
                            {
                                CreateDate = user.CreateDate,
                                Email = user.Email,
                                Confirm = true,
                                UserId = user.Id,
                                User = user
                            };
                            _db.Participants.Add(participant);
                            _db.SaveChanges();


                            return RedirectToAction("Participants");

                        }
                        else
                        {
                            var list_of_errors = result.Errors.ToList();
                            foreach (var error in list_of_errors)
                            {
                                if (error.Code.Contains("Password"))
                                {
                                    ModelState.AddModelError("password", error.Description);
                                }
                                else if (error.Code.Contains("User"))
                                {
                                    ModelState.AddModelError("username", error.Description);
                                }
                                else if (error.Code.Contains("Email"))
                                {
                                    ModelState.AddModelError("email", error.Description);
                                }
                            }
                        }
                    }
                    else
                        ModelState.AddModelError("password", "Podane hasło i powtórzone hasło musi się zgadzać.");
                }
                else
                    ModelState.AddModelError("username", "Nazwa użytkownika jest już zajęta.");
            }
            return View(participantVM);
        }

        [HttpGet]
        public async Task<IActionResult> Update(string userId)
        {
            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                UserCreateEditVM userVM = new UserCreateEditVM { UserName = user.UserName, Email = user.Email, UserId = user.Id };
                return View(userVM);
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        [HttpGet]
        public async Task<IActionResult> UpdateParticipant(string userId)
        {
            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                var participant = _db.Participants.FirstOrDefault(p => p.UserId == user.Id);
                if (participant == null)
                {
                    return NotFound();
                }
                ParticipantCreateEditVM participantVM = new ParticipantCreateEditVM { UserName = user.UserName, Email = participant.Email, FirstName = participant.FirstName, LastName = participant.LastName, Age = participant.Age, Gender = participant.Gender, Description = participant.Description, UserId = user.Id };

                return View(participantVM);
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(UserCreateEditVM userVM)
        {
            if (ModelState.IsValid)
            {
                User user = await _userManager.FindByIdAsync(userVM.UserId);
                bool change_userName = false;
                bool change_email = false;
                bool change_password = false;

                if (user != null)
                {
                    IdentityResult valid = await _userValidator.ValidateAsync(_userManager, user);
                    if (!string.IsNullOrEmpty(userVM.UserName) && userVM.UserName != user.UserName)
                    {
                        user.UserName = userVM.UserName;
                        valid = await _userValidator.ValidateAsync(_userManager, user);
                        if (!valid.Succeeded)
                        {
                            AddErrorsFromResult(valid);
                            return View(userVM);
                        }
                        change_userName = true;
                    }                   

                    IdentityResult validEmail = await _userValidator.ValidateAsync(_userManager, user);
                    if (!string.IsNullOrEmpty(userVM.Email) && userVM.Email != user.Email)
                    {
                        user.Email = userVM.Email;
                        validEmail = await _userValidator.ValidateAsync(_userManager, user);
                        if (!validEmail.Succeeded)
                        {
                            AddErrorsFromResult(validEmail);
                            return View(userVM);
                        }
                        change_email = true;
                    }

                    IdentityResult validPass = null;
                    if ((!string.IsNullOrEmpty(userVM.Password)) && (!string.IsNullOrEmpty(userVM.ConfirmPassword)) && (!string.IsNullOrEmpty(userVM.OldPassword)) && (userVM.OldPassword != userVM.Password) && (userVM.Password == userVM.ConfirmPassword))
                    {
                        validPass = await _passwordValidator.ValidateAsync(_userManager, user, userVM.Password);
                        if (validPass.Succeeded)
                        {
                            var result = _userManager.ChangePasswordAsync(user, userVM.OldPassword, userVM.Password);
                            if (result.Result.Succeeded)
                            {
                                user.PasswordHash = _passwordHasher.HashPassword(user, userVM.Password);
                                change_password = true;
                            }
                        }
                        else
                        {
                            AddErrorsFromResult(validPass);
                            return View(userVM);
                        }
                    }
                    else if ((!string.IsNullOrEmpty(userVM.OldPassword)) && (!string.IsNullOrEmpty(userVM.Password)) && (userVM.OldPassword == userVM.Password))
                    {
                        ModelState.AddModelError("oldpassword", "Stare hasło i nowe hasło musi być różne.");
                        return View(userVM);
                    }
                    else if (userVM.Password != userVM.ConfirmPassword)
                    {
                        ModelState.AddModelError("password", "Nowe hasło i powtórzone hasło muszą się zgadzać.");
                        return View(userVM);
                    }


                    if (change_userName || change_email || change_password)
                    {
                        IdentityResult result = await _userManager.UpdateAsync(user);
                        if (result.Succeeded)
                        {
                            return RedirectToAction("Index");
                        }
                        else
                        {

PsychologicalTestApp/Controllers/TestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace PsychologicalTestApp.Controllers
{
    public class TestController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

PsychologicalTestApp/Views/Admin/CreateParticipant.cshtml
@model ParticipantCreateEditVM
@section navbar_Admin {
    <section class="navbar_Admin">
        @Html.Partial("_Navbar_Admin")
    </section>
}

<link rel="stylesheet" href="~/css/create_user1.css" />

<div class="content_flex">
    <div class="card">
        <div class="card-header">
            <h3><strong>Utwórz pacjenta</strong></h3>
            <button onclick="window.location.href='Index'" type="button" class="close">&times;</button>
        </div>
        <div class="card-body">
            <form asp-action="CreateParticipant" asp-controller="Admin" method="post" class="form-horizontal" role="form">
                <div asp-validation-summary="ModelOnly" id="summary" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="UserName" class="control-label"></label>
                    <input asp-for="UserName" class="form-control">
                    <span asp-validation-for="UserName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Email" class="control-label"></label>
                    <input type="email" asp-for="Email" class="form-control">
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Password" class="control-label"></label>
                    <input asp-for="Password" class="form-control">
                    <span asp-validation-for="Password" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ConfirmPassword" class="control-label"></label>
                    <input asp-for="ConfirmPassword" class="form-control">
                    <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                </div>
                <label class="person-label">Dane osobowe</label>
                <div class="card-footer">
                    <div class="form-group">
                        <label asp-for="FirstName" class="control-label"></label>
                        <input type="text" asp-for="FirstName" class="form-control">
                        <span asp-validation-for="FirstName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="LastName" class="control-label"></label>
                        <input type="text" asp-for="LastName" class="form-control">
                        <span asp-validation-for="LastName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Gender" class="control-label"></label>
                        <select class="form-control" asp-for="Gender" asp-items="Html.GetEnumSelectList(typeof(PsychologicalTestApp.Models.Enums.Gender))">
                            <option selected="selected" value="">Wybierz</option>
                        </select>
                        <span asp-validation-for="Gender" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Age" class="control-label"></label>
                        <input type="number" asp-for="Age" class="form-control" min="1" max="116" />
                        <span asp-validation-for="Age" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <input type="text" asp-for="Description" class="form-control">
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-group btn-group">
                    <input type="submit" value="Utwórz" class="btn create_btn">
                    <input type="reset" value="Wyczyść" class="btn cancel_btn">
                </div>
            </form>
        </div>
    </div>
</div>

PsychologicalTestApp/Views/Admin/CreateTest.cshtml
<link rel="stylesheet" href="~/css/index5.css" />

@section navbar {
    <section class="navbar">
        @Html.Partial("_Navbar_Admin")
    </section>
}

@{
    ViewBag.Title = "Utwórz test";
}

<div class="container_flex">
    <div class="content-fluid">
        <div class="row" id="title">
            <div class="col-sm-10">
                <h2>@ViewBag.Title</h2>
            </div>
        </div>
    </div>
</div>

PsychologicalTestApp/Views/Admin/Index.cshtml
@model ParticipantListIndexVM

<link rel="stylesheet" href="~/css/index5.css" />

@section navbar {
    <section class="navbar">
        @Html.Partial("_Navbar_Admin")
    </section>
}

@{
    ViewBag.Title = "Lista użytkowników";
}

<div class="container_flex">
    <div class="content-fluid">
        <div class="row" id="title">
            <div class="col-sm-10">
                <h2>@ViewBag.Title</h2>
            </div>
            <div class="col-sm-2" style="float: right;">
                <div class="" style="float: right;">
                    <a href="@Url.Action("CreateParticipant")" class="btn pull-right">
                        <i class="material-icons" id="icon" data-toggle="tooltip" data-placement="bottom" title="Dodaj">&#xE147;</i>
                    </a>
                </div>
            </div>
        </div>
        <div id="ItemListDiv"></div>

        <div class="row">
            <nav aria-label="Page navigation">
                <ul class="pagination flex-wrap">
                    <li class="page-item @(Model.EnablePrevious ? " " : "disabled" )">
                        <a asp-route-currentPage="1"
                           class="page-link" aria-label="Frist">
                            <span aria-hidden="true">|<</span>
                            <span class="sr-only">Pierwszy</span>
                        </a>
                    </li>
                    <li class="page-item @(Model.EnablePrevious ? " " : "disabled" )">
                        <a asp-route-currentPage="@(Model.CurrentPage -1)"
                           class="page-link" aria-label="Next">
                            <span aria-hidden="true"><</span>
                            <span class="sr-only">Następny</span>
                        </a>
                    </li>
                    @for (var i = 1; i <= Model.TotalPages; i++)
                    {
                        <li class="page-item @(i == Model.CurrentPage ? "active" : "" )">
                            <a asp-route-currentPage="@i" class="page-link">@i</a>
                        </li>
                    }
                    <li class="page-item @(Model.EnableNext ? " " : "disabled" )">
                        <a asp-route-currentpage="@(Model.CurrentPage + 1)"
                           class="page-link" aria-label="Previous">
                            <span aria-hidden="true">></span>
                            <span class="sr-only">Poprzedni</span>
                        </a>
                    </li>
                    <li class="page-item @(Model.EnableNext ? " " : "disabled" )">
                        <a asp-route-currentPage="@Model.TotalPages"
                           class="page-link" aria-label="Last">
                            <span aria-hidden="true">>|</span>
                            <span class="sr-only">Ostatni</span>
                        </a>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
</div>

@section Scripts{
    <script type="text/javascript">
        var listUrl = '@Url.Action(nameof(AdminController.Participants))';

        $(document).ready(function () {
            initialize();
        });

        function initialize() {
            $.get(listUrl).done(function (data) {
                $('#ItemListDiv').html(data);
            });

        };

    </script>

}

PsychologicalTestApp/Views/Admin/Update.cshtml
@model UserCreateEditVM
@section navbar_Admin {
    <section class="navbar_Admin">
        @Html.Partial("_Navbar_Admin")
    </section>
}

<link rel="stylesheet" href="~/css/create_user1.css" />

<div class="content_flex">
    <div class="card">
        <div class="card-header">
            <h3><strong>Edytuj profil</strong></h3>
            <button onclick="window.location.href='Index'" type="button" class="close">&times;</button>
        </div>
        <div class="card-body">
            <form asp-action="Update" asp-controller="Admin" method="post" class="form-horizontal" role="form">
                <div asp-validation-summary="ModelOnly" id="summary" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="UserName" class="control-label"></label>
                    <input asp-for="UserName" class="form-control" placeholder="@Model.UserName">
                    <span asp-validation-for="UserName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Email" class="control-label"></label>
                    <input asp-for="Email" class="form-control" placeholder="@Model.Email">
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>

                <label class="person-label">Zmiana hasła</label>
                <div class="card-footer">
                    <div class="form-group">
                        <label asp-for="OldPassword" class="control-label"></label>
                        <input asp-for="OldPassword" class="form-control">
                        <span asp-validation-for="OldPassword" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Password" class="control-label"></label>
                        <input asp-for="Password" class="form-control">
                        <span asp-validation-for="Password" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ConfirmPassword" class="control-label"></label>
                        <input asp-for="ConfirmPassword" class="form-control">
                        <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                    </div>
                    <input asp-for="UserId" class="form-control" placeholder="@Model.UserId" hidden>
                    <div class="form-group btn-group">
                        <input type="submit" value="Zapisz" class="btn create_btn">
                        <input type="reset" value="Wyczyść" class="btn cancel_btn">
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

PsychologicalTestApp/Views/Admin/UpdateParticipant.cshtml
@model ParticipantCreateEditVM
@section navbar_Admin {
    <section class="navbar_Admin">
        @Html.Partial("_Navbar_Admin")
    </section>
}

<link rel="stylesheet" href="~/css/create_user1.css" />

<div class="content_flex">
    <div class="card">
        <div class="card-header">
            <h3><strong>Edytuj użytkownika</strong></h3>
            <button onclick="window.location.href='Index'" type="button" class="close">&times;</button>
        </div>
        <div class="card-body">
            <form asp-action="UpdateParticipant" asp-controller="Admin" method="post" class="form-horizontal" role="form">
                <div asp-validation-summary="ModelOnly" id="summary" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="UserName" class="control-label"></label>
                    <input asp-for="UserName" class="form-control" placeholder="@Model.UserName">
                    <span asp-validation-for="UserName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Email" class="control-label"></label>
                    <input type="email" asp-for="Email" class="form-control" placeholder="@Model.Email">
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
                <!--<label class="person-label">Zmiana hasła</label>
                <hr />
                <div class="form-group">
                    <label asp-for="Password" class="control-label"></label>
                    <input type="password" asp-for="Password" class="form-control" disabled>-->
                    @*<span asp-validation-for="Password" class="text-danger"></span>*@
                <!--</div>
                <div class="form-group">
                    <label asp-for="ConfirmPassword" class="control-label"></label>
                    <input type="password" asp-for="ConfirmPassword" class="form-control" disabled>-->
                    @*<span asp-validation-for="ConfirmPassword" class="text-danger"></span>*@
                <!--</div>-->
                <label class="person-label">Dane osobowe</label>
                <div class="card-footer">
                    <div class="form-group">
                        <label asp-for="FirstName" class="control-label"></label>
                        <input type="text" asp-for="FirstName" class="form-control" placeholder="@Model.FirstName">
                        <span asp-validation-for="FirstName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="LastName" class="control-label"></label>
                        <input type="text" asp-for="LastName" class="form-control" placeholder="@Model.LastName">
                        <span asp-validation-for="LastName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Gender" class="control-label"></label>
                        <select class="form-control" asp-for="Gender" asp-items="Html.GetEnumSelectList(typeof(PsychologicalTestApp.Models.Enums.Gender))">
                            <option selected="selected" value="">Wybierz</option>
                        </select>
                        <span asp-validation-for="Gender" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Age" class="control-label"></label>
                        <input type="number" asp-for="Age" class="form-control" min="1" max="116" />
                        <span asp-validation-for="Age" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <input type="text" asp-for="Description" class="form-control" placeholder="@Model.Description">
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <input asp-for="UserId" class="form-control" placeholder="@Model.UserId" hidden>
                <div class="form-group btn-group">
                    <input type="submit" value="Zapisz" class="btn create_btn">
                    <input type="reset" value="Wyczyść" class="btn cancel_btn">
                </div>
            </form>
        </div>
    </div>
</div>